server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            label: master
            server:
                git:
                    password: your password
                    searchPaths: respo
                    uri: https://github.com/forezp/SpringcloudConfig/
                    username: your username